# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image:  postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ~/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: ems
      POSTGRES_DB: emsdb
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
